### ISSUE TITLE
Bring back the footer

### ISSUE THREAD

**Issue by hamelsmu** [outerbounds/docs#30]
I would like a footer to put related links in.  Example of footer if you scroll to bottom of page https://docusaurus.io/docs

I believe we took this out of docs.metaflow.org but I would like the footer for Outerbounds

@obgibson @tuulos @hugobowne WDYT?

**Comment by hugobowne** [comment]
I think it's a great idea

**Comment by hamelsmu** [comment]
@obgibson would you mind bringing the footer back?  🙇🏽

**Comment by obgibson** [comment]
What would you like to put inside the footer?

**Comment by hamelsmu** [comment]
This was closed by https://github.com/outerbounds/docs/pull/47
